### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Xantastic** [HuiZhang0812/DiffusionAD#54]
Original Traceback (most recent call last):
  File "D:\anaconda3\envs\my_code\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\envs\my_code\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\my_code\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\13093\Desktop\paperCode\DiffusionAD-main\DiffusionAD-main\data\dataset_beta_thresh.py", line 274, in __getitem__
    augmented_image, anomaly_mask, has_anomaly  = self.perlin_synthetic(image,thresh,anomaly_path,cv2_image,thresh_path)
  File "C:\Users\13093\Desktop\paperCode\DiffusionAD-main\DiffusionAD-main\data\dataset_beta_thresh.py", line 207, in perlin_synthetic
    anomaly_img_augmented = aug(image=anomaly_source_img)
  File "D:\anaconda3\envs\my_code\lib\site-packages\imgaug\augmenters\meta.py", line 2008, in __call__
    return self.augment(*args, **kwargs)
  File "D:\anaconda3\envs\my_code\lib\site-packages\imgaug\augmenters\meta.py", line 1979, in augment
    batch_aug = self.augment_batch_(batch, hooks=hooks)
  File "D:\anaconda3\envs\my_code\lib\site-packages\imgaug\augmenters\meta.py", line 645, in augment_batch_
    hooks=hooks)
  File "D:\anaconda3\envs\my_code\lib\site-packages\imgaug\augmenters\meta.py", line 3127, in _augment_batch_
    hooks=hooks
  File "D:\anaconda3\envs\my_code\lib\site-packages\imgaug\augmenters\meta.py", line 645, in augment_batch_
    hooks=hooks)
  File "D:\anaconda3\envs\my_code\lib\site-packages\imgaug\augmenters\color.py", line 2471, in _augment_batch_
    image_hsv, hue_i, saturation_i)
  File "D:\anaconda3\envs\my_code\lib\site-packages\imgaug\augmenters\color.py", line 2501, in _transform_image_cv2
    table_hue = cls._LUT_CACHE[0]

**Comment by HuiZhang0812** [comment]
This issye seems to be caused by incorrect configuration of the path.

**Comment by HuiZhang0812** [comment]
This issue seems to be caused by an incorrect configuration of the path.
